### ISSUE TITLE
erver counter for new stuff isn't aligned with the rest

### ISSUE THREAD

**Issue by MiniDigger** [MiniDigger/thelounge-theme-mininapse#15]
<fnutt> MiniDigger: By the way, another issue... Server counter for new stuff isn't aligned with the rest.
<fnutt> If you type /msg nickserv help, you'll see it doesn't align to the right anymore.

**Comment by fnutt** [comment]
This is fixed by https://github.com/MiniDigger/thelounge-theme-mininapse/pull/27
